[package]
name = "visualize"
version = "0.0.1"
authors = ["Christian M<chriamue@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
transit-grid = { path="../.." }
egui_graphs = "0.5.3"
egui = "0.22"
eframe = "0.22"
geo = "0.25.0"
petgraph = "0.6"
rand = "0.8"